### ISSUE TITLE
IndexOutOfBoundsException, SDK1.10.2

### ISSUE THREAD

**Issue by charischung** [Netvent/storyly-mobile#105]
Fatal Exception: java.lang.IndexOutOfBoundsException: Invalid index 2, size is 2
       at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
       at java.util.ArrayList.get(ArrayList.java:308)
       at com.appsamurai.storyly.data.cache.a.a(ImageCacheManager.kt:6)
       at com.appsamurai.storyly.storylylist.StorylyListRecyclerView.onScrollStateChanged(StorylyListRecyclerView.kt:5)
       at androidx.recyclerview.widget.RecyclerView.dispatchOnScrollStateChanged(RecyclerView.java:5202)
       at androidx.recyclerview.widget.RecyclerView.setScrollState(RecyclerView.java:1550)
       at androidx.recyclerview.widget.RecyclerView.cancelScroll(RecyclerView.java:3444)
       at androidx.recyclerview.widget.RecyclerView.onTouchEvent(RecyclerView.java:3422)
       at android.view.View.dispatchTouchEvent(View.java:9994)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2794)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2501)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2801)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2516)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2801)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2516)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2801)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2516)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2801)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2516)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2801)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2516)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2801)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2516)
       at jd.overseas.market.home.widget.nested.NestedParentRecyclerView.dispatchTouchEvent(NestedParentRecyclerView.java:121)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2841)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2516)
       at com.scwang.smartrefresh.layout.SmartRefreshLayout.dispatchTouchEvent(SmartRefreshLayout.java:918)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2841)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2516)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2841)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2516)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2841)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2516)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2841)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2516)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2841)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2516)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2841)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2516)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2841)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2516)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2841)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2516)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2841)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2516)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2841)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2516)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2841)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2516)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2841)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2516)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2841)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2516)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2841)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2516)
       at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2823)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1848)
       at android.app.Activity.dispatchTouchEvent(Activity.java:3047)
       at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2784)
       at android.view.View.dispatchPointerEvent(View.java:10229)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5403)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5239)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4679)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4732)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4698)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4840)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4706)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4897)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4679)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4732)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4698)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4706)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4679)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7376)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7254)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7215)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7486)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(InputEventReceiver.java)
       at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
       at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7450)
       at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7513)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
       at android.view.Choreographer.doCallbacks(Choreographer.java:695)
       at android.view.Choreographer.doFrame(Choreographer.java:625)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7231)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by yigcal** [comment]
Hi @charischung,

We’ve changed the implementation of this flow in Android SDK v1.11.0 which makes this issue obsolete. Please check with the latest version and let us know if you run into the same error.
