### ISSUE TITLE
OutOfMemoryError SDK1.10.2

### ISSUE THREAD

**Issue by charischung** [Netvent/storyly-mobile#106]
Fatal Exception: java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start(Thread.java:883)
       at com.android.volley.i.a(RequestQueue.java:152)
       at com.android.volley.toolbox.m.a(Volley.java:64)
       at com.android.volley.toolbox.m.a(Volley.java:94)
       at com.android.volley.toolbox.m.a(Volley.java:104)
       at com.appsamurai.storyly.analytics.b.a(StorylyTracker.kt:492)
       at com.appsamurai.storyly.analytics.b.a(StorylyTracker.kt:1)
       at com.appsamurai.storyly.StorylyView.onWindowFocusChanged(StorylyView.kt:8)
       at android.view.View.dispatchWindowFocusChanged(View.java:13767)
       at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1481)
       at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1485)
       at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1485)
       at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1485)
       at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1485)
       at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1485)
       at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1485)
       at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1485)
       at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1485)
       at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1485)
       at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1485)
       at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1485)
       at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1485)
       at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1485)
       at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1485)
       at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1485)
       at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1485)
       at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1485)
       at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1485)
       at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1485)
       at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1485)
       at android.view.ViewRootImpl.handleWindowFocusChanged(ViewRootImpl.java:2941)
       at android.view.ViewRootImpl.access$1100(ViewRootImpl.java:147)
       at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4612)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7650)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by yigcal** [comment]
Hi @charischung,

We did a significant improvement for the memory management in Android SDK v1.11.0. Please check with the latest version.
