### ISSUE TITLE
IndexOutOfBoundsException in SDK 1.11.1

### ISSUE THREAD

**Issue by charischung** [Netvent/storyly-mobile#111]
Fatal Exception: java.lang.IndexOutOfBoundsException: toIndex = 4
at java.util.ArrayList.subListRangeCheck(ArrayList.java:1016)
at java.util.ArrayList.subList(ArrayList.java:1008)
at com.appsamurai.storyly.storylylist.StorylyListRecyclerView.onScrollStateChanged(StorylyListRecyclerView.kt:7)
at androidx.recyclerview.widget.RecyclerView.dispatchOnScrollStateChanged(RecyclerView.java:5202)
at androidx.recyclerview.widget.RecyclerView.setScrollState(RecyclerView.java:1550)
at androidx.recyclerview.widget.RecyclerView.stopScroll(RecyclerView.java:2493)
at androidx.recyclerview.widget.RecyclerView.scrollToPosition(RecyclerView.java:1744)
at com.appsamurai.storyly.storylylist.StorylyListRecyclerView$c$a.afterChange(Delegates.kt:191)
at kotlin.properties.ObservableProperty.setValue(ObservableProperty.kt:41)
at com.appsamurai.storyly.storylylist.StorylyListRecyclerView.setAdapterData$storyly_release(StorylyListRecyclerView.kt:2)
at com.appsamurai.storyly.StorylyView$d.a(StorylyView.kt:11)
at com.appsamurai.storyly.StorylyView$d.invoke(StorylyView.kt:1)
at com.appsamurai.storyly.data.o.invoke(StorylyDataManager.kt:65)
at com.appsamurai.storyly.data.j.a(StorylyDataManager.kt:797)
at com.appsamurai.storyly.data.j.a(StorylyDataManager.kt:11)
at com.appsamurai.storyly.data.n.run(StorylyDataManager.kt:1)
at android.os.Handler.handleCallback(Handler.java:790)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:7000)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

**Comment by levent-oral** [comment]
Hello @charischung ,

We've made a fix for this issue in [Android SDK 1.13.0](https://github.com/Netvent/storyly-mobile/blob/master/android/RELEASENOTES.md#1130). Please check with that.

Thanks!
