### ISSUE TITLE
Story View crashes with story containing emojis 

### ISSUE THREAD

**Issue by anus-ali** [Netvent/storyly-mobile#129]
Issue tracker is **ONLY** used for reporting Android SDK related bugs.

## Environment Details
**Storyly SDK Version: 1.13.4** ---
**Android SDK Version:30 ---
**Device Model: Pixel 3a ---
**Device OS Version: 11 ---
**Additional Info: If a story has an emoji it crashes just by opening it ---

## Expected Behavior
I should be able to view story contain emoji in android

## Current Behavior
It is crashing when opening a story

## Crash Logs

2021-08-12 04:06:52.222 20244-20244/com.sadapay.app.dev E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sadapay.app.dev, PID: 20244
    java.lang.IllegalStateException: Not initialized yet
        at androidx.core.util.Preconditions.checkState(Preconditions.java:96)
        at androidx.emoji.text.EmojiCompat.process(EmojiCompat.java:742)
        at androidx.emoji.text.EmojiCompat.process(EmojiCompat.java:702)
        at androidx.emoji.text.EmojiCompat.process(EmojiCompat.java:666)
        at androidx.emoji.text.EmojiCompat.process(EmojiCompat.java:634)
        at com.appsamurai.storyly.storylypresenter.storylylayer.n.a(StorylyEmojiView.kt:43)
        at com.appsamurai.storyly.storylypresenter.storylylayer.n$a.run(View.kt:2)
        at androidx.core.view.OneShotPreDrawListener.onPreDraw(OneShotPreDrawListener.java:71)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1088)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2745)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1721)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7598)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
        at android.view.Choreographer.doCallbacks(Choreographer.java:790)
        at android.view.Choreographer.doFrame(Choreographer.java:725)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by levent-oral** [comment]
Hello @anus-ali,

We've using [EmojiCompat](https://developer.android.com/reference/androidx/emoji/text/EmojiCompat) to show emojis in our components as it's suggested in [Emoji Compatibility Docs](https://developer.android.com/guide/topics/ui/look-and-feel/emoji-compat). Also, We're using [Downloadeble Fonts Configuration](https://developer.android.com/guide/topics/ui/look-and-feel/emoji-compat#downloadable-fonts) to reduce size of Storyly Android SDK. However, when device doesn't contain Google Play Services, Downloadable Fonts doesn't work as intended. To overcome this issue, you need to use [Bundled Fonts Configuration](https://developer.android.com/guide/topics/ui/look-and-feel/emoji-compat#bundled-fonts) an initialize in application side. 

Please note that, documentation suggests support version of emoji library, we suggest using [AndroidX release version of Emoji Library](https://developer.android.com/jetpack/androidx/releases/emoji). 

Thanks,

**Comment by anus-ali** [comment]
Thanks for this it has worked for me. I am closing this bug.
