### ISSUE TITLE
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by yasincidem** [Netvent/storyly-mobile#131]
## Environment Details
**Storyly SDK Version:** 1.13.5
**Device Model:** Device Model Independent
**Device OS Version:** 7, 9, 10, 11

App is in foreground when this crash occurs.

```  
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=7; index=-1
       at java.util.ArrayList.get(ArrayList.java:439)
       at com.appsamurai.storyly.storylypresenter.g.onScrollStateChanged(g.java:191)
       at androidx.recyclerview.widget.RecyclerView.dispatchOnScrollStateChanged(RecyclerView.java:5376)
       at androidx.recyclerview.widget.RecyclerView.setScrollState(RecyclerView.java:1618)
       at androidx.recyclerview.widget.RecyclerView.stopScroll(RecyclerView.java:2626)
       at androidx.recyclerview.widget.RecyclerView.scrollToPosition(RecyclerView.java:1812)
       at com.appsamurai.storyly.storylypresenter.g$b.afterChange(g.java:40)
       at kotlin.properties.ObservableProperty.setValue(ObservableProperty.java:41)
       at com.appsamurai.storyly.storylypresenter.g.setSelectedStorylyGroupIndex(g.java:11)
       at com.appsamurai.storyly.storylypresenter.b$b.afterChange(b.java:40)
       at kotlin.properties.ObservableProperty.setValue(ObservableProperty.java:41)
       at com.appsamurai.storyly.b.onShow(b.java:5)
       at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1430)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:255)
       at android.app.ActivityThread.main(ActivityThread.java:8194)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

 ```

**Comment by levent-oral** [comment]
Hello @yasincidem,

We couldn't the issue directly. We've tried to understand the issue from the logs and checked the possible scenarios. 

We've improved the codebase to prevent this issue happening in [1.15.1](https://github.com/Netvent/storyly-mobile/blob/master/android/RELEASENOTES.md#1151-23092021) version. 

Thanks,

**Comment by levent-oral** [comment]
Hello @yasincidem ,

This is also related with [#134](https://github.com/Netvent/storyly-mobile/issues/134#issuecomment-958962859), We've reproduced and fixed a issue related with this in [Android SDK 1.17.0 version](https://github.com/Netvent/storyly-mobile/blob/master/android/RELEASENOTES.md#1170-21102021). Moreover, [comment on #134 issue](https://github.com/Netvent/storyly-mobile/issues/134#issuecomment-958962859) suggests a fix for a similar issue.

Thanks,

**Comment by yasincidem** [comment]
Hi @levent-oral,

Sorry to come up with this again. This issue actually still occurs. Here is the device models affected by this and stack trace.

<img width="443" alt="image" src="https://user-images.githubusercontent.com/13544246/170360835-561164bd-8c3d-4ba9-98f5-d07180ac09a3.png">


```

Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
       at java.util.ArrayList.get(ArrayList.java:439)
       at com.appsamurai.storyly.storylypresenter.d.onScrollStateChanged(StorylyGroupRecyclerView.kt:226)
       at androidx.recyclerview.widget.RecyclerView.dispatchOnScrollStateChanged(RecyclerView.java:5376)
       at androidx.recyclerview.widget.RecyclerView.setScrollState(RecyclerView.java:1618)
       at androidx.recyclerview.widget.RecyclerView.stopScroll(RecyclerView.java:2626)
       at androidx.recyclerview.widget.RecyclerView.scrollToPosition(RecyclerView.java:1812)
       at com.appsamurai.storyly.storylypresenter.d$f.afterChange(Delegates.kt:40)
       at kotlin.properties.ObservableProperty.setValue(ObservableProperty.kt:41)
       at com.appsamurai.storyly.storylypresenter.d.setSelectedStorylyGroupIndex(StorylyGroupRecyclerView.kt:1)
       at com.appsamurai.storyly.storylypresenter.b$g.afterChange(Delegates.kt:40)
       at kotlin.properties.ObservableProperty.setValue(ObservableProperty.kt:41)
       at com.appsamurai.storyly.StorylyView.a(StorylyView.kt:74)
       at com.appsamurai.storyly.StorylyView$$InternalSyntheticLambda$0$5244003d7b1f55818293928019fc91b2ea97bf2310ad30f37dabb54353e9b983$0.onShow(StorylyView.java:6)
       at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1747)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8653)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

```

Can we somehow prevent the get() method from taking in the value -1 ?  (By the way all crashes occurs because of index "-1")
Does it need a simple if statement like ` if(position == RecyclerView.NO_POSITION) return`

Thanks in advance.
