### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException

### ISSUE THREAD

**Issue by yasincidem** [Netvent/storyly-mobile#132]
## Environment Details
**Storyly SDK Version:**  1.13.5
**Android SDK Version:** Device Model Independent
**Device Model:** Device Model Independent
**Device OS Version:** OS version independent

App is in foreground when this crash occurs.

``` 
Fatal Exception: java.lang.IllegalStateException: Fragment already added: q{9df04f7} (b64b482a-6952-4cd1-9c19-f511d2aabaae tag=StorylyDialogFragment)
       at androidx.fragment.app.FragmentStore.addFragment(FragmentStore.java:92)
       at androidx.fragment.app.FragmentManager.addFragment(FragmentManager.java:1367)
       at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:387)
       at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:1851)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1759)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1703)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1646)
       at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:480)
       at android.os.Handler.handleCallback(Handler.java:907)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

**Comment by levent-oral** [comment]
Hello @yasincidem,

We couldn't the issue directly. We've tried to understand the issue from the logs and checked the possible scenarios. 

We've improved the codebase to prevent this issue happening in [1.15.1](https://github.com/Netvent/storyly-mobile/blob/master/android/RELEASENOTES.md#1151-23092021) version. This is not direct solution, please update the latest version and let us know if the issue continues.

Thanks,
