### ISSUE TITLE
StrictMode policy violation

### ISSUE THREAD

**Issue by sergyabanzhy** [Netvent/storyly-mobile#142]
Issue tracker is **ONLY** used for reporting Android SDK related bugs.

## Environment Details
**Storyly SDK Version:*1.17.0*
**Android SDK Version:*Any* 
**Device Model:*Any*
**Device OS Version:*Any*
**Additional Info:** 

## Expected Behavior
StorylyDataManager releases all allocated resources

## Current Behavior
`StrictMode: StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
        at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1877)
        at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:286)
        at java.io.FileInputStream.finalize(FileInputStream.java:493)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:289)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:276)
        at java.lang.Daemons$Daemon.run(Daemons.java:137)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.Throwable: Explicit termination method 'close' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:237)
        at java.io.FileInputStream.<init>(FileInputStream.java:174)
        at android.app.ContextImpl.openFileInput(ContextImpl.java:600)
        at android.content.ContextWrapper.openFileInput(ContextWrapper.java:206)
        at android.content.ContextWrapper.openFileInput(ContextWrapper.java:206)
        at com.appsamurai.storyly.data.l.a(StorylyDataManager.kt:91)
        at com.appsamurai.storyly.data.p.run(StorylyDataManager.kt:1)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) `

**Comment by levent-oral** [comment]
Hello @sergyabanzhy ,

We've made a fix for this issue, it'll be available in the next patch release. We'll let you know when it's released. 

Thanks,

**Comment by levent-oral** [comment]
Hello @sergyabanzhy ,

We've released [Android SDK 1.18.1](https://github.com/Netvent/storyly-mobile/blob/master/android/RELEASENOTES.md#1181-26112021) which contains a fix for this issue. 

Thanks,
