### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by auxDK** [Netvent/storyly-mobile#153]
Issue tracker is **ONLY** used for reporting Android SDK related bugs.

## Environment Details
Storyly SDK Version:1.18.3
Android SDK Version:Any
Device Model:Any
Device OS Version:Any

## Expected Behavior

No crash 

## Current Behavior

Crash app 

```
Fatal Exception: java.lang.NoClassDefFoundError: jf1
       at com.google.android.exoplayer2.ExoPlayer$Builder.<init>(ExoPlayer.java:440)
       at com.appsamurai.storyly.storylypresenter.storylylayer.k.a(StorylyExoVideoView.kt:36)
       at com.appsamurai.storyly.storylypresenter.storylylayer.o.invoke(StorylyLayerContainerView.kt:591)
       at com.appsamurai.storyly.storylypresenter.storylylayer.a.a(LayerMetadataManager.kt:255)
       at com.appsamurai.storyly.storylypresenter.storylylayer.a.b(LayerMetadataManager.kt:105)
       at com.appsamurai.storyly.storylypresenter.storylylayer.q.run(View.kt:6)
       at androidx.core.view.OneShotPreDrawListener.onPreDraw(OneShotPreDrawListener.java:71)
       at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1014)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2620)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1544)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7602)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
       at android.view.Choreographer.doCallbacks(Choreographer.java:686)
       at android.view.Choreographer.doFrame(Choreographer.java:622)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7331)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by auxDK** [comment]
Hi @levent-oral , 
Directly not include dependencies  ExoPlayer but right now I find in my project version 2.16.0
