### ISSUE TITLE
App crash when we upload a video to an story

### ISSUE THREAD

**Issue by bala-t2s** [Netvent/storyly-mobile#182]
Issue tracker is **ONLY** used for reporting React Native SDK related bugs.

We have integrated Storyly in our application. When we try view video story, app getting crashed in Android alone.

App crashed and unable to see video story.

Storyly Version: 1.22.0
React Native SDK Version: 0.63.4
All Android devices - OS 10, 11, 12

## Environment Details
**Storyly SDK Version:** 1.22.0
**React Native SDK Version:** 0.63.4
**Platform:**
- [ * ] Android - Yes
- [ ] iOS
**Device Model:** All Android Devices
**Device OS Version:** 10, 11, 12
**Additional Info:**

## Expected Behavior
Video story should play

## Current Behavior
App Crashed

## Steps to Reproduce

1. Integrate storyly to react native app
2. Create a story with video
3. Try to see the video story in React Native - Android App

Crash Details:
`Fatal Exception: java.lang.AbstractMethodError: abstract method "void com.google.android.exoplayer2.Player$Listener.onLoadingChanged(boolean)"
       at com.google.android.exoplayer2.ExoPlayerImpl.lambda$updatePlaybackInfo$20(ExoPlayerImpl.java:1902)
       at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$ZvZZ5dY_PSUTkrxZ4N2V_kASjtc.invoke(:4)
       at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:281)
       at com.google.android.exoplayer2.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:190)
       at com.google.android.exoplayer2.util.-$$Lambda$ListenerSet$NbKDn9xtItiyMgYZmjIx_Sv1FFQ.run(:6)
       at com.google.android.exoplayer2.util.ListenerSet.flushEvents(ListenerSet.java:211)
       at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:1947)
       at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:1774)
       at com.google.android.exoplayer2.ExoPlayerImpl.lambda$new$1$ExoPlayerImpl(ExoPlayerImpl.java:306)
       at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$nOBJYkeEQ2uz3sBKLToLWmzrgZk.run(:4)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8680)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)`

**Comment by wass08** [comment]
Same issue after upgrading from 1.18

**Comment by sangeethkumarv** [comment]
Facing the same :(
