### ISSUE TITLE
com.appsamurai.storyly.storylypresenter.d.onScrollStateChanged crash

### ISSUE THREAD

**Issue by yasincidem** [Netvent/storyly-mobile#183]
Hi @levent-oral,

Sorry to come up with this again. #131 This issue actually still occurs(even with the version `1.21.2`). Here is the device models affected by this and stack trace.

<img width="443" alt="image" src="https://user-images.githubusercontent.com/13544246/170360835-561164bd-8c3d-4ba9-98f5-d07180ac09a3.png">

```

Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
       at java.util.ArrayList.get(ArrayList.java:439)
       at com.appsamurai.storyly.storylypresenter.d.onScrollStateChanged(StorylyGroupRecyclerView.kt:226)
       at androidx.recyclerview.widget.RecyclerView.dispatchOnScrollStateChanged(RecyclerView.java:5376)
       at androidx.recyclerview.widget.RecyclerView.setScrollState(RecyclerView.java:1618)
       at androidx.recyclerview.widget.RecyclerView.stopScroll(RecyclerView.java:2626)
       at androidx.recyclerview.widget.RecyclerView.scrollToPosition(RecyclerView.java:1812)
       at com.appsamurai.storyly.storylypresenter.d$f.afterChange(Delegates.kt:40)
       at kotlin.properties.ObservableProperty.setValue(ObservableProperty.kt:41)
       at com.appsamurai.storyly.storylypresenter.d.setSelectedStorylyGroupIndex(StorylyGroupRecyclerView.kt:1)
       at com.appsamurai.storyly.storylypresenter.b$g.afterChange(Delegates.kt:40)
       at kotlin.properties.ObservableProperty.setValue(ObservableProperty.kt:41)
       at com.appsamurai.storyly.StorylyView.a(StorylyView.kt:74)
       at com.appsamurai.storyly.StorylyView$$InternalSyntheticLambda$0$5244003d7b1f55818293928019fc91b2ea97bf2310ad30f37dabb54353e9b983$0.onShow(StorylyView.java:6)
       at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1747)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8653)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

```

Can we somehow prevent the get() method from taking in the value -1 ?  (By the way all crashes occurs because of index "-1")
Does it need a simple if statement like ` if(position == RecyclerView.NO_POSITION) return`

Thanks in advance.

**Comment by GalacticTitan** [comment]
Please let us know when this can be fixed.

**Comment by GalacticTitan** [comment]
We are having issue on latest 1.24.1 flutter sdk also.

**Comment by klamborowski** [comment]
We have same issue on 1.24.0
```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=9; index=-1
       at java.util.ArrayList.get(ArrayList.java:439)
       at com.appsamurai.storyly.storylypresenter.d.onScrollStateChanged(StorylyGroupRecyclerView.kt:240)
       at androidx.recyclerview.widget.RecyclerView.dispatchOnScrollStateChanged(RecyclerView.java:5376)
       at androidx.recyclerview.widget.RecyclerView.setScrollState(RecyclerView.java:1618)
       at androidx.recyclerview.widget.RecyclerView.stopScroll(RecyclerView.java:2626)
       at androidx.recyclerview.widget.RecyclerView.scrollToPosition(RecyclerView.java:1812)
       at com.appsamurai.storyly.storylypresenter.d$f.afterChange(Delegates.kt:40)
       at kotlin.properties.ObservableProperty.setValue(ObservableProperty.kt:41)
       at com.appsamurai.storyly.storylypresenter.d.setSelectedStorylyGroupIndex(StorylyGroupRecyclerView.kt:1)
       at com.appsamurai.storyly.storylypresenter.b$g.afterChange(Delegates.kt:40)
       at kotlin.properties.ObservableProperty.setValue(ObservableProperty.kt:41)
       at com.appsamurai.storyly.StorylyView.a(StorylyView.kt:96)
       at com.appsamurai.storyly.StorylyView$$InternalSyntheticLambda$1$3722b8849faafa9cd7ab8fa75e7576393bc17456e2a0cca62107a0c2c938556c$0.onShow(StorylyView.java:6)
       at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1464)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:233)
       at android.os.Looper.loop(Looper.java:344)
       at android.app.ActivityThread.main(ActivityThread.java:8248)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)
```

**Comment by alicja-ogonowska** [comment]
Same issue happening with Flutter SDK 1.26.5:

```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=8; index=-1
       at java.util.ArrayList.get(ArrayList.java:439)
       at com.appsamurai.storyly.storylypresenter.e.onScrollStateChanged(e.java:160)
       at androidx.recyclerview.widget.RecyclerView.dispatchOnScrollStateChanged(RecyclerView.java:7)
       at androidx.recyclerview.widget.RecyclerView.setScrollState(RecyclerView.java:13)
       at androidx.recyclerview.widget.RecyclerView.stopScroll(RecyclerView.java:1)
       at androidx.recyclerview.widget.RecyclerView.scrollToPosition(RecyclerView.java:5)
       at com.appsamurai.storyly.storylypresenter.e$g.afterChange(e.java:49)
       at kotlin.properties.ObservableProperty.setValue(ObservableProperty.java:16)
       at com.appsamurai.storyly.storylypresenter.e.setSelectedStorylyGroupIndex(e.java:11)
       at com.appsamurai.storyly.storylypresenter.b$g.afterChange(b.java:22)
       at kotlin.properties.ObservableProperty.setValue(ObservableProperty.java:16)
       at com.appsamurai.storyly.StorylyView.a(StorylyView.java:43)
       at com.appsamurai.storyly.-$$Lambda$EORfdLuFfExTEUAnY_ho0IKeEEU.onShow(-.java:6)
       at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1831)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8751)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Comment by levent-oral** [comment]
Hello,

We've improved our codebase in [Storyly Android SDK@1.32.6](https://github.com/Netvent/storyly-mobile/blob/master/android/RELEASENOTES.md#1326-05062023) version. 

Thanks,
