### ISSUE TITLE
StorylyLayerContainerView.kt line 483 crash 

### ISSUE THREAD

**Issue by MilindTestbook** [Netvent/storyly-mobile#204]
After loading storyly users are getting the below crash 

Error Log: 

`
Fatal Exception: java.util.ConcurrentModificationException
       at java.util.ArrayList$Itr.next(ArrayList.java:860)
       at com.appsamurai.storyly.storylypresenter.storylylayer.t$e.invoke(StorylyLayerContainerView.kt:483)
       at com.appsamurai.storyly.storylypresenter.storylylayer.t$a.a(StorylyLayerContainerView.kt:3)
       at com.appsamurai.storyly.storylypresenter.storylylayer.t.g(StorylyLayerContainerView.kt:5)
       at com.appsamurai.storyly.storylypresenter.m.n(StorylyGroupView.kt:5)
       at com.appsamurai.storyly.storylypresenter.m.d(StorylyGroupView.kt:7)
       at com.appsamurai.storyly.storylypresenter.m.a(StorylyGroupView.kt:1021)
       at com.appsamurai.storyly.storylypresenter.p.invoke(StorylyGroupView.kt:3)
       at com.appsamurai.storyly.storylypresenter.a$b.a(ActionManager.kt:7)
       at com.appsamurai.storyly.storylypresenter.a$f.invoke(ActionManager.kt:18)
       at com.appsamurai.storyly.storylypresenter.f1.a(TouchHandler.kt:125)
       at com.appsamurai.storyly.storylypresenter.m.a(StorylyGroupView.kt:269)
       at com.appsamurai.storyly.storylypresenter.m$$InternalSyntheticLambda$1$000bbf7327dd28a6e473d0ab2efb87684b77af20a01ed65f330e64c6ead11b07$0.onTouch(m.java:2)
       at android.view.View.dispatchTouchEvent(View.java:14372)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3857)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:733)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1922)
       at android.app.Dialog.dispatchTouchEvent(Dialog.java:1008)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:691)
       at android.view.View.dispatchPointerEvent(View.java:14644)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6523)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6310)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5748)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5801)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5767)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5923)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5775)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5980)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5748)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5801)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5767)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5775)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5748)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8907)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8768)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8721)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9043)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:194)
       at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(InputEventReceiver.java)
       at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:183)
       at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:8983)
       at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:9070)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:996)
       at android.view.Choreographer.doCallbacks(Choreographer.java:794)
       at android.view.Choreographer.doFrame(Choreographer.java:722)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:981)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7948)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
`

## Environment Details
**Storyly SDK Version: ** --- 1.24.0
**Device Model: Realme - ** --- realme 3
**Device OS Version: ** --- Android 10
**Additional Info:** ---
After upgrading storyly to the version 1.24.0 we started facing this issue 

## Steps to Reproduce
1. After loading storyly users are facing this issue

**Comment by levent-oral** [comment]
Hello @MilindTestbook ,

We've improved the codebase to address this issue in [Storyly Android SDK@1.28.2](https://github.com/Netvent/storyly-mobile/blob/master/android/RELEASENOTES.md#1282-18122022). Please update and check the results. Let us know if the issue persists. 

We've made some changes on codebase using stack trace due to non-reproducibility of the issue on our end. 

Thanks,
