### ISSUE TITLE
Android crash on v1.26.3 

### ISSUE THREAD

**Issue by romanikv** [Netvent/storyly-mobile#243]
Issue tracker is **ONLY** used for reporting Android SDK related bugs.

I have started receiving some crashes connected with StorylyLayerContainerView

## Environment Details
**Storyly SDK Version:** 1.26.3
**Android SDK Version:** 29-32
**Device Model:** Samsung, Huawei, Motorola and others 
**Device OS Version:** 10-12

## Current Behavior (Stack Trace)

```
Fatal Exception: java.util.ConcurrentModificationException
       at java.util.ArrayList$Itr.next(ArrayList.java:860)
       at com.appsamurai.storyly.storylypresenter.storylylayer.t$e.invoke(StorylyLayerContainerView.kt:496)
       at com.appsamurai.storyly.storylypresenter.storylylayer.t$a.a(StorylyLayerContainerView.kt:3)
       at com.appsamurai.storyly.storylypresenter.storylylayer.t.g(StorylyLayerContainerView.kt:5)
       at com.appsamurai.storyly.storylypresenter.o.n(StorylyGroupView.kt:5)
       at com.appsamurai.storyly.storylypresenter.o.d(StorylyGroupView.kt:7)
       at com.appsamurai.storyly.storylypresenter.o.a(StorylyGroupView.kt:1426)
       at com.appsamurai.storyly.storylypresenter.s.invoke(StorylyGroupView.kt:3)
       at com.appsamurai.storyly.storylypresenter.a$b.a(ActionManager.kt:7)
       at com.appsamurai.storyly.storylypresenter.a$f.invoke(ActionManager.kt:17)
       at com.appsamurai.storyly.storylypresenter.i1.a(TouchHandler.kt:125)
       at com.appsamurai.storyly.storylypresenter.o.a(StorylyGroupView.kt:215)
       at com.appsamurai.storyly.storylypresenter.o$$InternalSyntheticLambda$1$ef24cc43d1cab33cc48bb0d8dcb43161ec3acdc36aad5b53aa440a9f102109a3$0.onTouch(o.java:2)
       at android.view.View.dispatchTouchEvent(View.java:14320)

**Comment by aklamborowski-fm** [comment]
I'm facing this issue too. 

It seems to be related to https://github.com/Netvent/storyly-mobile/issues/204

Looking forward for fix.

**Comment by klamborowski** [comment]
I'm facing this issue too. 

It seems to be related to https://github.com/Netvent/storyly-mobile/issues/204

Looking forward for fix.

**Comment by levent-oral** [comment]
Hello @romanikv and @klamborowski ,

We've improved the codebase to address this issue in [Storyly Android SDK@1.28.2](https://github.com/Netvent/storyly-mobile/blob/master/android/RELEASENOTES.md#1282-18122022). Please update and check the results. Let us know if the issue persists. 

We've made some changes on codebase using stack trace due to non-reproducibility of the issue on our end. 

Thanks,
