### ISSUE TITLE
Android crash on v1.26.1 in React Native

### ISSUE THREAD

**Issue by cengselcuk** [Netvent/storyly-mobile#254]
We have started receiving some crashes on various Android phones. Crashlytics shows 87 crash events affecting 17 users. We didn't make a change in Storyly version, just a fresh issue we observe in Crashlytics after we published a new package in Play Store.

## Environment Details
**Storyly SDK Version:** 1.26.1
**React Native SDK Version:** 0.63.4

- Android 
**Device Models:** Samsung, Xiaomi, Oppo and others 
**Device OS Version:** 10-11-12

## Stack Trace

> Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'com.appsamurai.storyly.StoryGroupType com.appsamurai.storyly.data.w.h' on a null object reference
       at com.appsamurai.storyly.data.o.h(StorylyDataManager.kt:7)
       at com.appsamurai.storyly.data.o.b(StorylyDataManager.kt:886)
       at com.appsamurai.storyly.data.o.a(StorylyDataManager.kt:13)
       at com.appsamurai.storyly.data.o.a(StorylyDataManager.kt:4)
       at com.appsamurai.storyly.data.-$$Lambda$nH874Nkg_TjxATdn7O24AN1pgs8.run(:4)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:8037)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

**Comment by levent-oral** [comment]
Hello @cengselcuk ,

We've fixed this issue in Storyly Android SDK with 1.27.+ versions. You need to update storyly-react-native to [storyly-react-native@1.29.1, latest version](https://github.com/Netvent/storyly-mobile/blob/master/react-native/storyly-react-native/RELEASENOTES.md#1291-10012023) to have a fix for this issue. 

Thanks,
