### ISSUE TITLE
StorylyGroupRecyclerView.kt line 226 crash

### ISSUE THREAD

**Issue by MilindTestbook** [Netvent/storyly-mobile#255]
After scrolling through storyly views, users are getting the below crash

Fatal Exception: java.lang.IllegalArgumentException: Called attach on a child which is not detached: a{33025f2 position=3 id=-1, oldPos=-1, pLpos:-1 not recyclable(1) no parent} com.appsamurai.storyly.storylypresenter.a{c6dac21 VFED..... ......ID 0,0-720,1544 #7f0a1520 app:id/st_storyly_group_recycler_view}, adapter:com.appsamurai.storyly.storylypresenter.a$c@7aa8846, layout:com.appsamurai.storyly.storylypresenter.StorylyGroupRecyclerView$linearLayoutManager$2$1@5458a07, context:DashboardActivity@a175212
       at androidx.recyclerview.widget.RecyclerView$5.attachViewToParent(RecyclerView.java:953)
       at androidx.recyclerview.widget.ChildHelper.attachViewToParent(ChildHelper.java:239)
       at androidx.recyclerview.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:8883)
       at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8860)
       at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8848)
       at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1645)
       at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
       at androidx.recyclerview.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1395)
       at androidx.recyclerview.widget.LinearLayoutManager.scrollHorizontallyBy(LinearLayoutManager.java:1124)
       at androidx.recyclerview.widget.RecyclerView.scrollStep(RecyclerView.java:1969)
       at androidx.recyclerview.widget.RecyclerView.scrollByInternal(RecyclerView.java:2071)
       at androidx.recyclerview.widget.RecyclerView.scrollBy(RecyclerView.java:1880)
       at com.appsamurai.storyly.storylypresenter.g.a(StorylyGroupRecyclerView.kt:226)
       at com.appsamurai.storyly.storylypresenter.g$$InternalSyntheticLambda$2$c2b825ce958284fd5f4346f7793ffd69211c8b55ad17aa58238759048cb4bad8$0.onAnimationUpdate(g.java:4)
       at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1558)
       at android.animation.ValueAnimator.setCurrentFraction(ValueAnimator.java:684)
       at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:647)
       at android.animation.ValueAnimator.start(ValueAnimator.java:1079)
       at android.animation.ValueAnimator.start(ValueAnimator.java:1098)
       at com.appsamurai.storyly.storylypresenter.g.a(StorylyGroupRecyclerView.kt:224)
       at com.appsamurai.storyly.storylypresenter.g.invoke(StorylyGroupRecyclerView.kt:1)
       at com.appsamurai.storyly.storylypresenter.o.d(StorylyGroupView.kt:5)
       at com.appsamurai.storyly.storylypresenter.b1.invoke(StorylyGroupView.kt:7)
       at com.appsamurai.storyly.storylypresenter.storylylayer.t0.invoke(StorylyLayerContainerView.kt:3)
       at com.appsamurai.storyly.storylypresenter.storylylayer.q$c.onPlayerError(StorylyExoVideoView.kt:1)
       at com.appsamurai.storyly.exoplayer2.core.ExoPlayerImpl.lambda$release$5(ExoPlayerImpl.java:977)
       at com.appsamurai.storyly.exoplayer2.core.ExoPlayerImpl.$r8$lambda$tuNLvOgPFvqciCJ8qf9VS21HdXo(ExoPlayerImpl.java)
       at com.appsamurai.storyly.exoplayer2.core.ExoPlayerImpl$$InternalSyntheticLambda$3$1b0c0fb6bc878ddd8eb75e43a14a6c79dfa8430bd16a5ffa67c88f94dd93dc22$0.invoke(ExoPlayerImpl.java:2)
       at com.appsamurai.storyly.exoplayer2.common.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:281)
       at com.appsamurai.storyly.exoplayer2.common.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:190)
       at com.appsamurai.storyly.exoplayer2.common.util.ListenerSet.$r8$lambda$Oi-QcwTo1qeX8ekbjjsDhx8f4gg(ListenerSet.java)
       at com.appsamurai.storyly.exoplayer2.common.util.ListenerSet$$InternalSyntheticLambda$4$26d38c87285df7d109b46551de4eb58f9cd3858e4add5f1524d8d23316f8803b$0.run(ListenerSet.java:6)
       at com.appsamurai.storyly.exoplayer2.common.util.ListenerSet.flushEvents(ListenerSet.java:211)
       at com.appsamurai.storyly.exoplayer2.common.util.ListenerSet.sendEvent(ListenerSet.java:226)
       at com.appsamurai.storyly.exoplayer2.core.ExoPlayerImpl.release(ExoPlayerImpl.java:974)
       at com.appsamurai.storyly.storylypresenter.storylylayer.q.c(StorylyExoVideoView.kt:5)
       at com.appsamurai.storyly.storylypresenter.storylylayer.t$e.invoke(StorylyLayerContainerView.kt:511)
       at com.appsamurai.storyly.storylypresenter.storylylayer.t$a.a(StorylyLayerContainerView.kt:1)
       at com.appsamurai.storyly.storylypresenter.storylylayer.t.g(StorylyLayerContainerView.kt:5)
       at com.appsamurai.storyly.storylypresenter.o.n(StorylyGroupView.kt:5)
       at com.appsamurai.storyly.storylypresenter.o.q(StorylyGroupView.kt:2)
       at com.appsamurai.storyly.storylypresenter.e$c.a(StorylyGroupRecyclerView.kt:3)
       at com.appsamurai.storyly.storylypresenter.e$c.onViewDetachedFromWindow(StorylyGroupRecyclerView.kt:1)
       at androidx.recyclerview.widget.RecyclerView.dispatchChildDetached(RecyclerView.java:7852)
       at androidx.recyclerview.widget.RecyclerView.removeDetachedView(RecyclerView.java:4523)
       at androidx.recyclerview.widget.RecyclerView$LayoutManager.removeAndRecycleScrapInt(RecyclerView.java:9541)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:4381)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4031)
       at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
       at android.view.View.layout(View.java:22090)
       at android.view.ViewGroup.layout(ViewGroup.java:6358)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:22090)
       at android.view.ViewGroup.layout(ViewGroup.java:6358)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:22090)
       at android.view.ViewGroup.layout(ViewGroup.java:6358)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:22090)
       at android.view.ViewGroup.layout(ViewGroup.java:6358)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
       at android.view.View.layout(View.java:22090)
       at android.view.ViewGroup.layout(ViewGroup.java:6358)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:783)
       at android.view.View.layout(View.java:22090)
       at android.view.ViewGroup.layout(ViewGroup.java:6358)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3239)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2735)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1821)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7916)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:980)
       at android.view.Choreographer.doCallbacks(Choreographer.java:804)
       at android.view.Choreographer.doFrame(Choreographer.java:739)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:965)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:264)
       at android.app.ActivityThread.main(ActivityThread.java:7581)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)

## Environment Details
**Storyly SDK Version: 1.28.2** 
**Device Model: TECNO MOBILE LIMITED, Pouvoir 4** 
**Device OS Version: Android 10**

## Steps to Reproduce
1. Scroll through storyly

**Comment by levent-oral** [comment]
Hello @MilindTestbook ,

Is this behavior reproducible on all devices or is it device specific? 

Thanks,

**Comment by MilindTestbook** [comment]
Happening on Xiaomi, Samsung, OPPO, Realme devices

**Comment by amusselwhite-rtg** [comment]
We are also seeing this error happen occasionally in our releases using the `storyly-rn-legacy` package. Is it resolved in the latest android release?
