### ISSUE TITLE
App crashes when opening in Android 

### ISSUE THREAD

**Issue by 7patricia** [Netvent/storyly-mobile#73]
## Environment Details
**Storyly SDK Version:** 1.9.2
**React Native SDK Version:** 1.9.1
**Platform:**
- [X] Android 
- [ ] iOS

**Device Model:** Galaxy S8
**Device OS Version:** 9

## Expected Behavior
Just trying to open the App with Storyly in it.

## Current Behavior
App crashes with the following error when opening the screen which has Storyly in it:
```
2021-03-25 15:39:34.704 4881-4881/com.uphold.wallet E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.uphold.wallet, PID: 4881
    java.lang.IllegalStateException: GeneratedAppGlideModuleImpl is implemented incorrectly. If you've manually implemented this class, remove your implementation. The Annotation processor will generate a correct implementation.
        at com.bumptech.glide.Glide.throwIncorrectGlideModule(Glide.java:344)
        at com.bumptech.glide.Glide.getAnnotationGeneratedGlideModules(Glide.java:336)
        at com.bumptech.glide.Glide.get(Glide.java:179)
        at com.bumptech.glide.Glide.getRetriever(Glide.java:749)
        at com.bumptech.glide.Glide.with(Glide.java:776)
        at com.appsamurai.storyly.data.cache.a.b(ImageCacheManager.kt:3)
        at com.appsamurai.storyly.data.cache.a.a(ImageCacheManager.kt:10)
        at com.appsamurai.storyly.data.cache.a$a.afterChange(Delegates.kt:69)
        at kotlin.properties.ObservableProperty.setValue(ObservableProperty.kt:41)
        at com.appsamurai.storyly.StorylyView$d.a(StorylyView.kt:13)
        at com.appsamurai.storyly.StorylyView$d.invoke(StorylyView.kt:1)
        at com.appsamurai.storyly.data.u.invoke(StorylyDataManager.kt:76)
        at com.appsamurai.storyly.data.l.a(StorylyDataManager.kt:923)
        at com.appsamurai.storyly.data.l.a(StorylyDataManager.kt:1274)
        at com.appsamurai.storyly.data.p.run(StorylyDataManager.kt:1)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: java.lang.NoSuchMethodException: com.bumptech.glide.GeneratedAppGlideModuleImpl.<init> [class android.content.Context]
        at java.lang.Class.getConstructor0(Class.java:2328)
        at java.lang.Class.getDeclaredConstructor(Class.java:2167)
        at com.bumptech.glide.Glide.getAnnotationGeneratedGlideModules(Glide.java:320)
        at com.bumptech.glide.Glide.get(Glide.java:179) 
        at com.bumptech.glide.Glide.getRetriever(Glide.java:749) 
        at com.bumptech.glide.Glide.with(Glide.java:776) 
        at com.appsamurai.storyly.data.cache.a.b(ImageCacheManager.kt:3) 
        at com.appsamurai.storyly.data.cache.a.a(ImageCacheManager.kt:10) 
        at com.appsamurai.storyly.data.cache.a$a.afterChange(Delegates.kt:69) 
        at kotlin.properties.ObservableProperty.setValue(ObservableProperty.kt:41) 
        at com.appsamurai.storyly.StorylyView$d.a(StorylyView.kt:13) 
        at com.appsamurai.storyly.StorylyView$d.invoke(StorylyView.kt:1) 
        at com.appsamurai.storyly.data.u.invoke(StorylyDataManager.kt:76) 
        at com.appsamurai.storyly.data.l.a(StorylyDataManager.kt:923) 
        at com.appsamurai.storyly.data.l.a(StorylyDataManager.kt:1274) 
        at com.appsamurai.storyly.data.p.run(StorylyDataManager.kt:1) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7050) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965) 
```

**Comment by levent-oral** [comment]
Hello @7patricia,

We're using Glide, but not custom implemented Glide module. It may be another library which uses this way, can you check it please? Duplicate usage of Glide may cause this type of problem. 

Moreover, there are similar issues with Glide page as well; specifically [4220](https://github.com/bumptech/glide/issues/4220). Also, some StackOverflow questions; [GeneratedAppGlideModule Error](https://stackoverflow.com/questions/56673917/failed-to-find-generatedappglidemodule-error) and [IllegalStateException with GeneratedAppGlideModuleImpl Error](https://stackoverflow.com/questions/58222340/glide-4-10-0-java-lang-illegalstateexception-generatedappglidemoduleimpl-is-i)

Can you check with them please to ensure that additional setup is required or not from app side? 

Thanks,

**Comment by SandroMachado** [comment]
Hi @levent-oral, 

The library that we are using that uses glide is: https://github.com/DylanVann/react-native-fast-image/blob/master/android/build.gradle#L65

We are not using any custom implementation, and checking the library I didn't see any custom implementation either. 

Do you have more suggestions?

**Comment by levent-oral** [comment]
We'll check using this dependency to reproduce the issue in a basic app. We'll let you know if we find anything. 

Thanks for the detail! 🎉

**Comment by levent-oral** [comment]
We've tested with react-native-fast-image, but we couldn't reproduce the issue. Please check #81 for details. 

However, we've checked with react-native-fast-image's source code and documentation, we've realized that it extends AppGlideModule, [FastImageGlideModule](https://github.com/DylanVann/react-native-fast-image/blob/master/android/src/main/java/com/dylanvann/fastimage/FastImageGlideModule.java). It is also mentioned [react-native-fast-image's documentation](https://github.com/DylanVann/react-native-fast-image#are-you-using-glide-already-using-an-appglidemodule) that there could be issue with AppGlideModule usage. Can you check it if this is the case on your side by following [AppGlideModule removal guideline](https://github.com/DylanVann/react-native-fast-image/blob/master/docs/app-glide-module.md)?

Moreover, there could be issue with ProGuard usage as stated [Using ProGuard](https://github.com/DylanVann/react-native-fast-image#are-you-using-proguard) section.

We're able to run and use both libraries in a Sample App, #81 . If there is a specific usage on your case, feel free to add commits to PR so we can reproduce it and check for solutions.

**Comment by levent-oral** [comment]
@SandroMachado, @7patricia, did you get a chance to look into this?
